#!/bin/bash

# Build script for IBudget - creates Windows Setup.exe and macOS .pkg installers
# Run this on macOS to generate proper .pkg files and cross-compile Windows .exe installers
# Uses Velopack (vpk) for Windows installer creation and pkgbuild for macOS .pkg

set -e

# Validate that we're running on macOS (required for pkgbuild and codesign tools)
if [ "$(uname -s)" != "Darwin" ]; then
    echo "Error: This script must be run on macOS." >&2
    exit 1
fi

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Load .env file if it exists
ENV_FILE="./.env"

if [ -f "$ENV_FILE" ]; then
    echo -e "${CYAN}Loading environment variables from .env file...${NC}"
    while IFS='=' read -r key value || [ -n "$key" ]; do
        # Skip comments and empty lines
        [[ $key =~ ^#.*$ ]] && continue
        [[ -z $key ]] && continue
        # Trim whitespace
        key=$(echo "$key" | xargs)
        value=$(echo "$value" | xargs)
        if [ -n "$key" ]; then
            export "$key=$value"
        fi
    done < "$ENV_FILE"
else
    echo -e "${YELLOW}No .env file found.${NC}"
fi

# Configuration
PROJECT_PATH="IBudget.GUI/IBudget.GUI.csproj"
RELEASES_PATH="./releases"
APP_NAME="Stacks"
APP_IDENTIFIER="com.stacks.app"
GITHUB_REPO="zlo120/IBudget"

# Always build both Windows and macOS
PLATFORMS=("win-x64" "osx-arm64")
echo -e "${CYAN}Building for platform(s): ${PLATFORMS[*]}${NC}"

# Get and increment version from .env
if [ -n "$VERSION" ]; then
    CURRENT_VERSION="$VERSION"
    echo -e "${CYAN}Current version: $CURRENT_VERSION${NC}"
    
    # Parse and increment version (major.minor.patch)
    if [[ $CURRENT_VERSION =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
        MAJOR="${BASH_REMATCH[1]}"
        MINOR="${BASH_REMATCH[2]}"
        PATCH="${BASH_REMATCH[3]}"
        
        # Increment patch version
        PATCH=$((PATCH + 1))
        VERSION="$MAJOR.$MINOR.$PATCH"
    else
        echo -e "${YELLOW}Invalid version format, resetting to 0.1.0${NC}"
        VERSION="0.1.0"
    fi
else
    echo -e "${YELLOW}No VERSION found in .env, starting at 0.1.0${NC}"
    VERSION="0.1.0"
fi

echo -e "${GREEN}New version: $VERSION${NC}"

# Update .env file with new version
if [ -f "$ENV_FILE" ]; then
    if grep -q "^VERSION=" "$ENV_FILE"; then
        sed -i.bak "s/^VERSION=.*/VERSION=$VERSION/" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
    else
        echo "VERSION=$VERSION" >> "$ENV_FILE"
    fi
fi

# Step 1: Clean previous builds
echo -e "${CYAN}Cleaning previous builds...${NC}"
rm -rf "$RELEASES_PATH"
mkdir -p "$RELEASES_PATH"

# Build for each platform
for RUNTIME in "${PLATFORMS[@]}"; do
    echo -e "\n${MAGENTA}========================================${NC}"
    echo -e "${MAGENTA}Building for $RUNTIME${NC}"
    echo -e "${MAGENTA}========================================\n${NC}"
    
    PUBLISH_PATH="./publish/$RUNTIME"
    
    # Clean platform-specific publish folder
    rm -rf "$PUBLISH_PATH"
    
    # Step 2: Publish the application
    echo -e "${CYAN}Publishing application for $RUNTIME...${NC}"
    dotnet publish "$PROJECT_PATH" -c Release -r "$RUNTIME" --self-contained true -o "$PUBLISH_PATH"
    
    if [ $? -ne 0 ]; then
        echo -e "${RED}Build failed for $RUNTIME!${NC}"
        exit 1
    fi
    
    # Step 3: Package
    if [ "$RUNTIME" == "win-x64" ]; then
        echo -e "${CYAN}Creating Windows installer (.exe) via Velopack cross-compile...${NC}"
        
        # Use vpk [win] directive to cross-compile Windows installer on macOS
        # Brackets are quoted to prevent shell glob expansion
        vpk "[win]" pack \
            -u "$APP_NAME" \
            -v "$VERSION" \
            -p "$PUBLISH_PATH" \
            -e IBudget.GUI.exe \
            -o "$RELEASES_PATH"
        
        if [ $? -ne 0 ]; then
            echo -e "${RED}Velopack packaging failed for Windows!${NC}"
            exit 1
        fi
        
        # Verify the Setup.exe was created
        SETUP_EXE=$(find "$RELEASES_PATH" -name "*-Setup.exe" | head -1)
        if [ -f "$SETUP_EXE" ]; then
            echo -e "${GREEN}Created Windows installer: $SETUP_EXE${NC}"
        else
            echo -e "${RED}Failed to create Windows Setup.exe!${NC}"
            exit 1
        fi
        
        # Verify releases.win.json was created by vpk
        if [ -f "$RELEASES_PATH/releases.win.json" ]; then
            echo -e "${GREEN}Created: $RELEASES_PATH/releases.win.json${NC}"
        else
            echo -e "${RED}releases.win.json was not generated by Velopack!${NC}"
            exit 1
        fi
        
        # Remove .nupkg file - not needed in the release
        find "$RELEASES_PATH" -name "*.nupkg" -delete
        
        echo -e "${YELLOW}NOTE: Windows installer is unsigned. Users may see 'Unknown Publisher' warning.${NC}"
        
    elif [ "$RUNTIME" == "osx-arm64" ]; then
        echo -e "${CYAN}Creating macOS .pkg installer for Apple Silicon (M series)...${NC}"
        
        # Create app bundle structure
        APP_BUNDLE="$PUBLISH_PATH/$APP_NAME.app"
        mkdir -p "$APP_BUNDLE/Contents/MacOS"
        mkdir -p "$APP_BUNDLE/Contents/Resources"
        
        # Copy executable and dependencies
        cp -R "$PUBLISH_PATH"/* "$APP_BUNDLE/Contents/MacOS/" 2>/dev/null || true
        rm -rf "$APP_BUNDLE/Contents/MacOS/$APP_NAME.app"  # Remove nested app bundle if created
        
        # Create Info.plist
        cat > "$APP_BUNDLE/Contents/Info.plist" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>IBudget.GUI</string>
    <key>CFBundleIdentifier</key>
    <string>$APP_IDENTIFIER</string>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundleVersion</key>
    <string>$VERSION</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>LSMinimumSystemVersion</key>
    <string>11.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSApplicationCategoryType</key>
    <string>public.app-category.finance</string>
</dict>
</plist>
EOF
        
        # Make executable
        chmod +x "$APP_BUNDLE/Contents/MacOS/IBudget.GUI"
        
        # Create .pkg installer using pkgbuild
        PKG_NAME="$APP_NAME-$VERSION-osx-arm64.pkg"
        PKG_PATH="$RELEASES_PATH/$PKG_NAME"
        
        echo -e "${CYAN}Building .pkg installer...${NC}"
        pkgbuild --root "$APP_BUNDLE" \
                 --identifier "$APP_IDENTIFIER" \
                 --version "$VERSION" \
                 --install-location "/Applications/$APP_NAME.app" \
                 "$PKG_PATH"
        
        if [ -f "$PKG_PATH" ]; then
            echo -e "${GREEN}Created: $PKG_PATH${NC}"
            
            # Calculate hashes
            SHA1=$(shasum -a 1 "$PKG_PATH" | awk '{print toupper($1)}')
            SHA256=$(shasum -a 256 "$PKG_PATH" | awk '{print toupper($1)}')
            SIZE=$(stat -f%z "$PKG_PATH" 2>/dev/null || stat -c%s "$PKG_PATH" 2>/dev/null)
            
            # Create releases.osx.json
            cat > "$RELEASES_PATH/releases.osx.json" << EOF
{
    "Assets": [
        {
            "PackageId": "$APP_NAME",
            "Version": "$VERSION",
            "Type": "Full",
            "FileName": "$PKG_NAME",
            "SHA1": "$SHA1",
            "SHA256": "$SHA256",
            "Size": $SIZE
        }
    ]
}
EOF
            echo -e "${GREEN}Created: $RELEASES_PATH/releases.osx.json${NC}"
        else
            echo -e "${RED}Failed to create .pkg for macOS!${NC}"
            exit 1
        fi
        
        # Also create a portable zip for users who prefer it
        ZIP_NAME="$APP_NAME-$VERSION-osx-arm64-portable.zip"
        ZIP_PATH="$RELEASES_PATH/$ZIP_NAME"
        echo -e "${CYAN}Creating portable zip...${NC}"
        cd "$PUBLISH_PATH" && zip -r "../../$ZIP_PATH" "$APP_NAME.app" && cd - > /dev/null
        
        if [ -f "$ZIP_PATH" ]; then
            echo -e "${GREEN}Created portable: $ZIP_PATH${NC}"
        fi
        
        echo -e "\n${YELLOW}NOTE: macOS .pkg is unsigned. Users may need to:${NC}"
        echo -e "${YELLOW}1. Right-click the .pkg and select 'Open'${NC}"
        echo -e "${YELLOW}2. Or go to System Preferences > Security & Privacy to allow it${NC}"
    fi
done

echo -e "\n${GREEN}Release packages created in: $RELEASES_PATH${NC}"

# List created files
echo -e "\n${CYAN}Created files:${NC}"
ls -la "$RELEASES_PATH"

# Step 5: Upload to GitHub Releases using GitHub API
# GITHUB_TOKEN is already exported from .env

if [ -n "$GITHUB_TOKEN" ]; then
    echo -e "\n${CYAN}Creating GitHub Release v$VERSION...${NC}"
    
    # Check if release already exists and delete it if so
    EXISTING_RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/$GITHUB_REPO/releases/tags/v$VERSION")
    
    EXISTING_ID=$(echo "$EXISTING_RESPONSE" | grep -o '"id": [0-9]*' | head -1 | grep -o '[0-9]*' || true)
    
    if [ -n "$EXISTING_ID" ]; then
        echo -e "${YELLOW}Release v$VERSION already exists (ID: $EXISTING_ID). Deleting...${NC}"
        curl -s -X DELETE \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$GITHUB_REPO/releases/$EXISTING_ID"
        
        # Also delete the tag so it can be recreated
        curl -s -X DELETE \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$GITHUB_REPO/git/refs/tags/v$VERSION" > /dev/null 2>&1 || true
        
        echo -e "${GREEN}Deleted existing release.${NC}"
        sleep 2
    fi
    
    # Create the release via GitHub API
    CREATE_RESPONSE=$(curl -s -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/$GITHUB_REPO/releases" \
        -d "{
            \"tag_name\": \"v$VERSION\",
            \"name\": \"v$VERSION\",
            \"body\": \"Release v$VERSION\",
            \"draft\": false,
            \"prerelease\": false
        }")
    
    RELEASE_ID=$(echo "$CREATE_RESPONSE" | grep -o '"id": [0-9]*' | head -1 | grep -o '[0-9]*' || true)
    UPLOAD_URL=$(echo "$CREATE_RESPONSE" | grep -o '"upload_url": "[^"]*"' | head -1 | sed 's/"upload_url": "//;s/{.*//' || true)
    
    if [ -z "$RELEASE_ID" ]; then
        echo -e "${YELLOW}Release may already exist, trying to fetch it...${NC}"
        FETCH_RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$GITHUB_REPO/releases/tags/v$VERSION")
        
        RELEASE_ID=$(echo "$FETCH_RESPONSE" | grep -o '"id": [0-9]*' | head -1 | grep -o '[0-9]*' || true)
        UPLOAD_URL=$(echo "$FETCH_RESPONSE" | grep -o '"upload_url": "[^"]*"' | head -1 | sed 's/"upload_url": "//;s/{.*//' || true)
    fi
    
    if [ -n "$RELEASE_ID" ] && [ -n "$UPLOAD_URL" ]; then
        echo -e "${GREEN}Release ID: $RELEASE_ID${NC}"
        
        # Upload all release assets
        upload_asset() {
            local FILE_PATH="$1"
            local CONTENT_TYPE="$2"
            local FILENAME=$(basename "$FILE_PATH")
            
            echo -e "${CYAN}Uploading $FILENAME...${NC}"
            UPLOAD_RESPONSE=$(curl -s -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Content-Type: $CONTENT_TYPE" \
                --data-binary @"$FILE_PATH" \
                "${UPLOAD_URL}?name=$FILENAME")
            
            if echo "$UPLOAD_RESPONSE" | grep -q '"state": "uploaded"'; then
                echo -e "${GREEN}Uploaded $FILENAME${NC}"
            else
                echo -e "${YELLOW}Upload response for $FILENAME: $(echo "$UPLOAD_RESPONSE" | grep -o '"message": "[^"]*"' || echo "check manually")${NC}"
            fi
        }
        
        # Upload Windows assets (Setup.exe, releases.win.json, assets.win.json, RELEASES)
        SETUP_EXE=$(find "$RELEASES_PATH" -name "*-Setup.exe" | head -1)
        if [ -f "$SETUP_EXE" ]; then
            upload_asset "$SETUP_EXE" "application/octet-stream"
        fi
        
        if [ -f "$RELEASES_PATH/releases.win.json" ]; then
            upload_asset "$RELEASES_PATH/releases.win.json" "application/json"
        fi
        
        if [ -f "$RELEASES_PATH/assets.win.json" ]; then
            upload_asset "$RELEASES_PATH/assets.win.json" "application/json"
        fi
        
        if [ -f "$RELEASES_PATH/RELEASES" ]; then
            upload_asset "$RELEASES_PATH/RELEASES" "application/octet-stream"
        fi
        
        # Upload macOS assets (.pkg, portable zip, releases.osx.json)
        PKG_FILE=$(find "$RELEASES_PATH" -name "*.pkg" | head -1)
        if [ -f "$PKG_FILE" ]; then
            upload_asset "$PKG_FILE" "application/octet-stream"
        fi
        
        OSX_ZIP_FILE=$(find "$RELEASES_PATH" -name "*portable.zip" | head -1)
        if [ -f "$OSX_ZIP_FILE" ]; then
            upload_asset "$OSX_ZIP_FILE" "application/zip"
        fi
        
        if [ -f "$RELEASES_PATH/releases.osx.json" ]; then
            upload_asset "$RELEASES_PATH/releases.osx.json" "application/json"
        fi
        
        echo -e "\n${GREEN}All assets uploaded to GitHub Release v$VERSION${NC}"
        echo -e "${CYAN}View at: https://github.com/$GITHUB_REPO/releases/tag/v$VERSION${NC}"
    else
        echo -e "${RED}Could not create or find release. Files are in $RELEASES_PATH - upload manually.${NC}"
        echo -e "${RED}API response: $CREATE_RESPONSE${NC}"
    fi
else
    echo -e "${YELLOW}Skipping GitHub upload (GITHUB_TOKEN not set in .env)${NC}"
    echo -e "${YELLOW}To upload, add GITHUB_TOKEN=your_token to your .env file${NC}"
fi

echo -e "\n${GREEN}Build complete!${NC}"
